import type { Metadata } from "next";
import Link from "next/link";

import "./globals.css";
import "zenn-content-css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <header className="border-b">
          <div className="container mx-auto p-2">
            <h1>
              <Link href={{ pathname: "/" }}>My Blog</Link>
            </h1>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
